### ISSUE TITLE
incorporate Google Firebase to save information

### ISSUE THREAD

**Issue by danieldealday** [danieldealday/Jool#13]
be sure to include authentication for the database so that information is saved

**Comment by viet-vo** [comment]
Other than the material that I have previously learned, is there any new stuff I need to look into to integrate Firebase?

**Comment by danieldealday** [comment]
> Other than the material that I have previously learned, is there any new stuff I need to look into to integrate Firebase?

@viet-vo I was actually going to close this Issue because, I was going to make the migration to Heroku instead.
